INSERT INTO geneticas (gen_nome, gen_descricao, gen_caracteristicas) VALUES
('Duroc', 'Raça americana conhecida pela excelente qualidade da carne.', 'Alta taxa de crescimento, carne marmorizada e boa conversão alimentar.'),
('Landrace', 'Raça originária da Dinamarca amplamente usada em cruzamentos comerciais.', 'Alta prolificidade, boa produção de leite e excelente habilidade materna.'),
('Yorkshire', 'Raça britânica muito versátil e produtiva.', 'Alta fertilidade, boa conformação e longevidade reprodutiva.'),
('Spotted', 'Raça americana com pelagem manchada.', 'Bom ganho de peso e rusticidade.'),
('Hereford', 'Raça americana facilmente reconhecida pela coloração marrom-avermelhada com branco.', 'Calmo, rústico e carne de boa qualidade.'),
('Gloucestershire Old Spot', 'Raça britânica tradicional.', 'Excelente mãe, boa para sistemas extensivos e carne de sabor delicado.'),
('Poland China', 'Raça americana de grande porte.', 'Alta conversão alimentar e boa produção de carne.'),
('Red Wattle', 'Raça americana de carne diferenciada.', 'Carne de sabor intenso e animais resistentes.'),
('Ossabaw Island', 'Raça americana originária da Ilha de Ossabaw.', 'Rústica, pequena e adaptada a ambientes difíceis.'),
('Vietnamita', 'Raça do Vietnã usada em cruzamentos e pets.', 'Pequeno porte e boa adaptabilidade.'),
('Basco', 'Raça francesa tradicional.', 'Carne de sabor refinado usada em charcutaria artesanal.'),
('Gascon', 'Raça francesa rústica.', 'Excelente resistência e carne de alta qualidade.'),
('Cinta Senese', 'Raça italiana da Toscana.', 'Carne marmorizada, usada em produtos típicos italianos.'),
('Nilo', 'Raça africana antiga do Egito.', 'Adaptada ao calor extremo e à escassez de água.'),
('Creole', 'Raça caribenha adaptada ao clima tropical.', 'Alta rusticidade, boa adaptação e resistência a doenças.');
